import {
  ModifierKey as MODIFIERS,
  ToolbarType as TOOLBARS,
  DisplayMode as DISPLAY_MODE,
  DecorationMode as DECORATION_MODE,
  MediaUploadErrorKey,
} from 'wix-rich-content-common';

export const COMMANDS = Object.freeze({
  TITLE: 'header-two',
  SUBTITLE: 'header-three',
  ALIGN_LEFT: 'left',
  ALIGN_RIGHT: 'right',
  ALIGN_CENTER: 'center',
  JUSTIFY: 'justify',
  NUMBERED_LIST: 'ordered-list-item',
  BULLET_LIST: 'unordered-list-item',
  CODE: 'code-block',
  BLOCKQUOTE: 'blockquote',
  BACKSPACE: 'backspace',
  DELETE: 'delete',
  TAB: 'tab',
  SHIFT_TAB: 'shiftTab',
  ESC: 'esc',
});

export const TEXT_TYPES = Object.freeze([
  'unstyled',
  'blockquote',
  'header-one',
  'header-two',
  'header-three',
  'header-four',
  'header-five',
  'header-six',
  'ordered-list-item',
  'unordered-list-item',
]);

export const CHARACTERS = Object.freeze({
  TAB: '\t',
});

export { MODIFIERS, TOOLBARS, DISPLAY_MODE, DECORATION_MODE };

export const KEYS_CHARCODE = {
  ENTER: 13,
  ESCAPE: 27,
};

export const FORMATTING_BUTTONS = Object.freeze({
  BOLD: 'Bold',
  ITALIC: 'Italic',
  UNDERLINE: 'Underline',
  TITLE: 'Title',
  BLOCKQUOTE: 'Blockquote',
  ALIGN_LEFT: 'AlignLeft',
  ALIGN_RIGHT: 'AlignRight',
  ALIGN_CENTER: 'AlignCenter',
  ALIGN_JUSTIFY: 'Justify',
  ORDERED_LIST: 'OrderedList',
  UNORDERED_LIST: 'UnorderedList',
  // plugins
  SPOILER: 'SPOILER',
  LINK: 'LINK',
  HEADINGS: 'HEADINGS',
  TEXT_COLOR: 'TEXT_COLOR',
  TEXT_HIGHLIGHT: 'TEXT_HIGHLIGHT',
  CODE_BLOCK: 'CODE_BLOCK',
  UNDO: 'UNDO',
  REDO: 'REDO',
  LINE_SPACING: 'LINE_SPACING',
  INCREASE_INDENT: 'INCREASE_INDENT',
  DECREASE_INDENT: 'DECREASE_INDENT',
});

export const INSERT_PLUGIN_BUTTONS = Object.freeze({
  IMAGE: 'ImagePlugin_InsertButton',
  GALLERY: 'GalleryPlugin_InsertButton',
  POLLS: 'Poll',
  DIVIDER: 'DividerPlugin_InsertButton',
  HTML: 'HTMLCodePlugin_InsertButton',
  VIDEO: 'VideoPlugin_InsertButton',
  INSTAGRAM: 'Instagram_InsertButton',
  YOUTUBE: 'YouTube_InsertButton',
  TIKTOK: 'TikTok_InsertButton',
  TWITTER: 'Twitter_InsertButton',
  STORES: 'Stores_InsertButton',
  BUTTON: 'ButtonPlugin_InsertButton',
  CODE_BLOCK: 'CodeblockPlugin_InsertButton',
  SOUND_CLOUD: 'SoundcloudPlugin_InsertButton',
  GIF: 'GIFPlugin_InsertButton',
  MAP: 'MapPlugin_InsertButton',
  FILE: 'UploadFilePlugin_InsertButton',
  EMOJI: 'EmojiPlugin_InsertButton',
  UNDO: 'UndoPlugin_InsertButton',
  REDO: 'RedoPlugin_InsertButton',
  TABLE: 'TablePlugin_InsertButton',
});

export const BUTTON_TYPES = Object.freeze({
  BUTTON: 'button',
  FILE: 'file',
  MODAL: 'modal',
  CUSTOM_BLOCK: 'custom-block',
  SEPARATOR: 'SEPARATOR',
  DROPDOWN: 'DROPDOWN',
  GROUP: 'GROUP',
});

export const ERROR_MAP = {
  [MediaUploadErrorKey.GENERIC]: 'UploadFile_Error_Generic_Toast',
  [MediaUploadErrorKey.QUOTA_STORAGE_VISITOR]: 'UploadFile_Error_StorageExceeded_Visitor',
  [MediaUploadErrorKey.QUOTA_STORAGE_OWNER]: 'UploadFile_Error_StorageExceeded_SiteOwner',
  [MediaUploadErrorKey.QUOTA_VIDEO_VISITOR]: 'UploadVideo_Error_StorageExceeded_Visitor',
  [MediaUploadErrorKey.QUOTA_VIDEO_OWNER]: 'UploadVideo_Error_StorageExceeded_SiteOwner',
  [MediaUploadErrorKey.SIZE_LIMIT]: 'UploadFile_Error_Size_Toast',
  [MediaUploadErrorKey.QUOTA_SINGLE_VIDEO_OWNER]: 'UploadVideo_Error_Video_Duration_SiteOwner',
  [MediaUploadErrorKey.MIME_TYPE_MISMATCH]: 'UploadFile_Error_Mimetype_Mismatch',
  [MediaUploadErrorKey.QUOTA_SINGLE_VIDEO_VISITOR]: 'UploadVideo_Error_Video_Duration_Visitor',
  [MediaUploadErrorKey.WMP_ERROR_GENERAL]: 'UploadFile_Error_WMP_General',
  [MediaUploadErrorKey.INVALID_SESSION]: 'UploadFile_Error_General_Logged_Out',
  [MediaUploadErrorKey.SESSION_EXPIRED]: 'UploadFile_Error_General_Logged_Out',
  [MediaUploadErrorKey.MISSING_WIX_SESSION]: 'UploadFile_Error_General_Logged_Out',
  [MediaUploadErrorKey.INCORRECT_FILE_INFO]: 'UploadFile_Error_Corrupt_File',
  [MediaUploadErrorKey.CORRUPT_FILE]: 'UploadFile_Error_Corrupt_File',
  [MediaUploadErrorKey.UNSUPPORTED_EXTENSION]: 'UploadFile_Error_Unsupported_Extension',
  [MediaUploadErrorKey.MISSING_HEADER]: 'UploadFile_Error_Corrupt_File',
  [MediaUploadErrorKey.FORMAT_CHUNK_MISSING]: 'UploadFile_Error_Corrupt_File',
  [MediaUploadErrorKey.EXT_FILE_AUTHORIZATION]: 'UploadFile_Error_External_File_Authorizaion',
  [MediaUploadErrorKey.EXT_FILE_FORBBIDEN]: 'UploadFile_Error_External_File_Authorizaion',
  [MediaUploadErrorKey.IMAGE_FORMAT]: 'UploadImage_Error_Unsupported_Image_Format',
  [MediaUploadErrorKey.CORRUPT_IMAGE]: 'UploadImage_Error_Corrupted_Image',
  [MediaUploadErrorKey.IMAGE_DIMENSIONS_EXCEEDED]: 'UploadImage_Error_Image_Dimensions_Exceeded',
  [MediaUploadErrorKey.MP4_STEREO_FORMAT]: 'UploadAudio_Error_Unsupported_Stereo_Format',
  [MediaUploadErrorKey.WAV_STEREO_FORMAT]: 'UploadAudio_Error_Unsupported_Stereo_Format',
  [MediaUploadErrorKey.WMA_BITRATE]: 'UploadAudio_Error_Unsupported_Bit_Rate',
  [MediaUploadErrorKey.WMA_BITRATE_LOSSY]: 'UploadAudio_Error_Unsupported_Bit_Rate',
  [MediaUploadErrorKey.MP4_BITRATE]: 'UploadAudio_Error_Unsupported_Bit_Rate',
  [MediaUploadErrorKey.MP3_UNSUPPORTED_STEREO]: 'UploadAudio_Error_MP3_Unsupported_Stereo_Format',
  [MediaUploadErrorKey.MP3_UNSUPPORTED_FORMAT]: 'UploadAudio_Error_MP3_Unsupported_Format',
  [MediaUploadErrorKey.WAV_SAMPLE_RATE]: 'UploadAudio_Error_Unsupported_Sample_Rate',
  [MediaUploadErrorKey.AAC_UNSUPPORTED_FORMAT]: 'UploadAudio_Error_aac_Unsupported_Format',
  [MediaUploadErrorKey.WAV_UNSUPPORTED_FORMAT]: 'UploadAudio_Error_wav_Unsupported_Format',
  [MediaUploadErrorKey.WAV_SAMPLE_SIZE]: 'UploadAudio_Error_Unsupported_Sample_Size',
  [MediaUploadErrorKey.WAV_CHUNK_SIZE]: 'UploadFile_Error_Corrupt_File',
  [MediaUploadErrorKey.AUDIO_CODEC]: 'UploadAudio_Error_Unsupported_Audio_Codec',
  [MediaUploadErrorKey.EMPTY_FILE]: 'UploadFile_Error_Empty_File',
  [MediaUploadErrorKey.MP4_UNSUPPORTED_FORMAT]: 'UploadAudio_Error_MP4_Unsupported_Format',
  [MediaUploadErrorKey.MP4_SAMPLE_RATE]: 'UploadAudio_Error_Unsupported_Sample_Rate',
  [MediaUploadErrorKey.VIDEO_BITRATE]: 'UploadVideo_Error_Unsupported_Bit_Rate',
  [MediaUploadErrorKey.VIDEO_DURATION_MISMATCH]: 'UploadVideo_Error_Video_Audio_Duration_Mismatch',
  [MediaUploadErrorKey.VIDEO_CODEC]: 'UploadVideo_Error_Unsupported_Video_Codec',
};
