export default [
  {
    id: '54d74308-2ada-413e-bc38-25d968afd1f7',
    name:
      '2-week course of intensive physical research, with a sense of plenty of time for process and discovery. Rooted in Ohad N',
    imageSrc: 'https://static.wixstatic.com/media/f5af78_997132ea0863425fbb0970d3fe1de2dc~mv2.jpg',
    description: '17 באוקטובר 2020, 19:00 – 30 באוקטובר 2020, 23:00 | Suzanna Baby Shop | Medan',
    html:
      '<style>.rtl {↵		direction: rtl;↵		}↵↵		.ltr {↵		direction: ltr;↵		}↵		.card {↵		width: 100%;↵		border: solid 1px #808080;↵		background-color: white;↵		}↵↵		.image {↵		background-size: cover;↵		background-repeat: no-repeat;↵		background-position: center center;↵		flex: 0 0 auto;↵		}↵↵		@media only screen and (min-width: 650px) {↵		.card {↵			display: flex;↵			flex-direction: row;↵		}↵↵		.image {↵			width: 185px;↵		}↵		}↵↵		@media only screen and (max-width: 649px) and (min-width: 280px) {↵		.card {↵			width: 280px;↵		}↵↵		.image {↵			padding-bottom: 56.25%;↵		}↵		}</style><div class="card ltr"><div style="background-image:url(https://static.wixstatic.com/media/f5af78_997132ea0863425fbb0970d3fe1de2dc~mv2.jpg)" class="image"></div><style>.content {↵		margin: 32px;↵		}↵↵		.title {↵		max-width: 306px;↵		font-family: LibreBaskerville;↵		font-size: 20px;↵		line-height: 1.4;↵		color: #000000;↵		}↵↵		.subtitle {↵		padding-top: 12px;↵		font-family: Avenir;↵		font-size: 14px;↵		line-height: 1.43;↵		color: #000000;↵		}↵↵		.right {↵		padding: 0 9.6px 0 9.6px;↵		}↵↵		.button {↵		width: 145px;↵		display: flex;↵		justify-content: center;↵		background-color: #000000;↵		}↵↵		.button:hover {↵			opacity: 0.7;↵		}↵↵		.button:focus {↵			opacity: 0.7;↵		}↵↵		.link {↵		padding: 8px 16px 8px 16px;↵		font-family: Avenir;↵		line-height: 1.5;↵		text-align: center;↵		color: #ffffff;↵		text-decoration: none;↵		}↵↵		@media only screen and (min-width: 650px) {↵↵		.content {↵			width: 100%;↵			display: flex;↵			justify-content: space-between;↵		}↵↵		.button {↵			height: 40px;↵		}↵		}↵↵		@media only screen and (max-width: 649px) and (min-width: 280px) {↵↵		.content {↵			margin: 20px;↵			flex-direction: column;↵		}↵↵		.title {↵			max-width: 240px;↵		}↵↵		.button {↵			width: 240px;↵			margin-top: 24px;↵		}↵		}</style><div class="content"><div><div class="title">2-week course of intensive physical research, with a sense of plenty of time for process and discovery. Rooted in Ohad N</div><div class="subtitle">17 באוקטובר 2020, 19:00 – 30 באוקטובר 2020, 23:00<span><span class="right">|</span>Suzanna Baby Shop | Medan</span></div></div><div class="button"><a class="link" href="https://www.wix.app/events/d4ec6294-d112-4962-9353-170889a40a78/54d74308-2ada-413e-bc38-25d968afd1f7/details?d=https://adie964.wixsite.com/vertical-embed-test/event-details/2-week-course-of-intensive-physical-research-with-a-sense-of-plenty-of-time-for-process-and-discovery-rooted-in-ohad-n" target="_blank">Register Now</a></div></div></div>',
  },
];
