export default [
  {
    id: '4c3330c5-d6cb-40a3-99ac-766c14dce93',
    name: 'Basic Baking Workshop',
    html:
      '<style>.rtl {↵		direction: rtl;↵		}↵↵		.ltr {↵		direction: ltr;↵		}↵		.card {↵		width: 100%;↵		border: solid 1px #808080;↵		background-color: white;↵		}↵↵		.image {↵		background-size: cover;↵		background-repeat: no-repeat;↵		background-position: center center;↵		flex: 0 0 auto;↵		}↵↵		@media only screen and (min-width: 650px) {↵		.card {↵			display: flex;↵			flex-direction: row;↵		}↵↵		.image {↵			width: 185px;↵		}↵		}↵↵		@media only screen and (max-width: 649px) and (min-width: 280px) {↵		.card {↵			width: 280px;↵		}↵↵		.image {↵			padding-bottom: 56.25%;↵		}↵		}</style><div class="card ltr"><div style="background-image:url(https://static.wixstatic.com/media/f5af78_5c6b5d749d7644c0a3cfe2797ad9e0bb~mv2.jpeg)" class="image"></div><style>.content {↵		margin: 32px;↵		}↵↵		.title {↵		max-width: 306px;↵		font-family: LibreBaskerville;↵		font-size: 20px;↵		line-height: 1.4;↵		color: #000000;↵		}↵↵		.subtitle {↵		padding-top: 12px;↵		font-family: Avenir;↵		font-size: 14px;↵		line-height: 1.43;↵		color: #000000;↵		}↵↵		.right {↵		padding: 0 9.6px 0 9.6px;↵		}↵↵		.button {↵		width: 145px;↵		display: flex;↵		justify-content: center;↵		background-color: #000000;↵		}↵↵		.button:hover {↵			opacity: 0.7;↵		}↵↵		.button:focus {↵			opacity: 0.7;↵		}↵↵		.link {↵		padding: 8px 16px 8px 16px;↵		font-family: Avenir;↵		line-height: 1.5;↵		text-align: center;↵		color: #ffffff;↵		text-decoration: none;↵		}↵↵		@media only screen and (min-width: 650px) {↵↵		.content {↵			width: 100%;↵			display: flex;↵			justify-content: space-between;↵		}↵↵		.button {↵			height: 40px;↵		}↵		}↵↵		@media only screen and (max-width: 649px) and (min-width: 280px) {↵↵		.content {↵			margin: 20px;↵			flex-direction: column;↵		}↵↵		.title {↵			max-width: 240px;↵		}↵↵		.button {↵			width: 240px;↵			margin-top: 24px;↵		}↵		}</style><div class="content"><div><div class="title">Basic Baking Workshop</div></div><div class="button"><a class="link" href="https://www.wix.app/bookings/d4ec6294-d112-4962-9353-170889a40a78/service/4c3330c5-d6cb-40a3-99ac-766c14dce931/details?d=https://adie964.wixsite.com/vertical-embed-test/bookings-checkout/basic-baking-workshop" target="_blank">Book Now</a></div></div></div>',
    imageSrc: 'https://static.wixstatic.com/media/f5af78_5c6b5d749d7644c0a3cfe2797ad9e0bb~mv2.jpeg',
    description: '120 ILS',
  },
];
