import { TEXT_BUTTONS } from 'wix-rich-content-editor-common';
export const desktopTextButtonList = [
  'Headings',
  '|',
  TEXT_BUTTONS.BOLD,
  TEXT_BUTTONS.ITALIC,
  TEXT_BUTTONS.UNDERLINE,
  'TextColor',
  'TextHighlight',
  TEXT_BUTTONS.TITLE,
  TEXT_BUTTONS.BLOCKQUOTE,
  '|',
  {
    tooltipKey: 'AlignTextDropdownButton_Tooltip',
    name: 'Alignment',
    dataHook: 'Alignment',
    buttons: [
      TEXT_BUTTONS.ALIGN_LEFT,
      TEXT_BUTTONS.ALIGN_CENTER,
      TEXT_BUTTONS.ALIGN_RIGHT,
      TEXT_BUTTONS.ALIGN_JUSTIFY,
    ],
  },
  TEXT_BUTTONS.ORDERED_LIST,
  TEXT_BUTTONS.UNORDERED_LIST,
  'DecreaseIndent',
  'IncreaseIndent',
  '|',
  'LineSpacing',
  'Link',
  'CodeBlock',
];

export const mobileTextButtonList = [
  'AddPlugin',
  'Headings',
  TEXT_BUTTONS.BOLD,
  TEXT_BUTTONS.ITALIC,
  TEXT_BUTTONS.UNDERLINE,
  'TextColor',
  'TextHighlight',
  TEXT_BUTTONS.TITLE,
  TEXT_BUTTONS.BLOCKQUOTE,
  TEXT_BUTTONS.ALIGN_LEFT,
  TEXT_BUTTONS.ALIGN_CENTER,
  TEXT_BUTTONS.ALIGN_RIGHT,
  TEXT_BUTTONS.ALIGN_JUSTIFY,
  TEXT_BUTTONS.ORDERED_LIST,
  TEXT_BUTTONS.UNORDERED_LIST,
  'DecreaseIndent',
  'IncreaseIndent',
  'LineSpacing',
  'Link',
  'CodeBlock',
  'Undo',
  'Redo',
];

export const pluginButtonNames = [
  'Instagram_InsertButton',
  'Twitter_InsertButton',
  'YouTube_InsertButton',
  'TikTok_InsertButton',
  'Stores_InsertButton',
  'ButtonPlugin_InsertButton',
  'Poll',
  'ImagePlugin_InsertButton',
  'GalleryPlugin_InsertButton',
  'VideoPlugin_InsertButton',
  'HTMLCodePlugin_InsertButton',
  'DividerPlugin_InsertButton',
  'CodeblockPlugin_InsertButton',
  'SoundcloudPlugin_InsertButton',
  'GIFPlugin_InsertButton',
  'MapPlugin_InsertButton',
  'UploadFilePlugin_InsertButton',
  'EmojiPlugin_InsertButton',
  'UndoPlugin_InsertButton',
  'RedoPlugin_InsertButton',
];

export { default as textAlignmentButton } from './TextAlignmentButton';
export { default as AddPluginButton } from './AddPluginButton';
export {
  boldButton,
  italicButton,
  underlineButton,
  titleButton,
  blockquoteButton,
  alignTextLeftButton,
  alignTextCenterButton,
  alignTextRightButton,
  alignTextJustifyButton,
  orderedListButton,
  unorderedListButton,
} from './TextButtons';
