export const desktopTextButtonList = [
  'Headings',
  '|',
  'Bold',
  'Italic',
  'Underline',
  'TextColor',
  'TextHighlight',
  'Title',
  'Blockquote',
  '|',
  'Alignment',
  'OrderedList',
  'UnorderedList',
  'DecreaseIndent',
  'IncreaseIndent',
  '|',
  'LineSpacing',
  'Link',
  'CodeBlock',
];

export const mobileTextButtonList = [
  'AddPlugin',
  'Headings',
  'Bold',
  'Italic',
  'Underline',
  'TextColor',
  'TextHighlight',
  'Title',
  'Blockquote',
  'AlignLeft',
  'AlignCenter',
  'AlignRight',
  'AlignJustify',
  'OrderedList',
  'UnorderedList',
  'DecreaseIndent',
  'IncreaseIndent',
  'LineSpacing',
  'Link',
  'CodeBlock',
  'Undo',
  'Redo',
];

export { default as textAlignmentButton } from './TextAlignmentButton';
export { default as AddPluginButton } from './AddPluginButton';
