export const mockCustoms = {
  h2: {
    font: 'normal normal normal 95px/1.4em lulo-clean-w01-one-bold,sans-serif',
    color: '#333333',
  },
  h3: {
    font:
      'normal normal normal 16px/1.4em din-next-w01-light,din-next-w02-light,din-next-w10-light,sans-serif',
    color: '#333333',
  },
  h4: {
    font: 'normal normal normal 28px/1.4em avenir-lt-w01_35-light1475496,sans-serif',
    color: '#333333',
  },
  h5: {
    font: 'normal normal normal 119px/1.4em avenir-lt-w01_35-light1475496,sans-serif',
    color: '#333333',
  },
  h6: {
    font: 'normal normal normal 34px/1.4em lulo-clean-w01-one-bold,sans-serif',
    color: '#333333',
  },
  p: {
    font: 'normal normal normal 28px/1.4em lulo-clean-w01-one-bold,sans-serif',
    color: '#333333',
  },
  link: {
    font: 'normal normal normal 24px/1.4em avenir-lt-w01_35-light1475496,sans-serif',
    color: '#333333',
  },
  hashtag: {
    font: 'normal normal normal 16px/1.4em avenir-lt-w01_35-light1475496,sans-serif',
    color: '#333333',
  },
  quote: {
    font: 'normal normal normal 15px/1.4em avenir-lt-w01_35-light1475496,sans-serif',
    color: '#333333',
  },
};

export const mockOutput = {
  'custom-h2Color': '#333333',
  'custom-h2Font': 'normal normal normal 95px/1.4em lulo-clean-w01-one-bold,sans-serif',
  'custom-h2FontFamily': undefined,
  'custom-h2FontSize': undefined,
  'custom-h2FontStyle': undefined,
  'custom-h2FontWeight': undefined,
  'custom-h2LineHeight': undefined,
  'custom-h2TextDecoration': undefined,
  'custom-h3Color': '#333333',
  'custom-h3Font':
    'normal normal normal 16px/1.4em din-next-w01-light,din-next-w02-light,din-next-w10-light,sans-serif',
  'custom-h3FontFamily': undefined,
  'custom-h3FontSize': undefined,
  'custom-h3FontStyle': undefined,
  'custom-h3FontWeight': undefined,
  'custom-h3LineHeight': undefined,
  'custom-h3TextDecoration': undefined,
  'custom-h4Color': '#333333',
  'custom-h4Font': 'normal normal normal 28px/1.4em avenir-lt-w01_35-light1475496,sans-serif',
  'custom-h4FontFamily': undefined,
  'custom-h4FontSize': undefined,
  'custom-h4FontStyle': undefined,
  'custom-h4FontWeight': undefined,
  'custom-h4LineHeight': undefined,
  'custom-h4TextDecoration': undefined,
  'custom-h5Color': '#333333',
  'custom-h5Font': 'normal normal normal 119px/1.4em avenir-lt-w01_35-light1475496,sans-serif',
  'custom-h5FontFamily': undefined,
  'custom-h5FontSize': undefined,
  'custom-h5FontStyle': undefined,
  'custom-h5FontWeight': undefined,
  'custom-h5LineHeight': undefined,
  'custom-h5TextDecoration': undefined,
  'custom-h6Color': '#333333',
  'custom-h6Font': 'normal normal normal 34px/1.4em lulo-clean-w01-one-bold,sans-serif',
  'custom-h6FontFamily': undefined,
  'custom-h6FontSize': undefined,
  'custom-h6FontStyle': undefined,
  'custom-h6FontWeight': undefined,
  'custom-h6LineHeight': undefined,
  'custom-h6TextDecoration': undefined,
  'custom-hashtagColor': '#333333',
  'custom-hashtagFont': 'normal normal normal 16px/1.4em avenir-lt-w01_35-light1475496,sans-serif',
  'custom-hashtagFontFamily': undefined,
  'custom-hashtagFontSize': undefined,
  'custom-hashtagFontStyle': undefined,
  'custom-hashtagFontWeight': undefined,
  'custom-hashtagLineHeight': undefined,
  'custom-hashtagTextDecoration': undefined,
  'custom-linkColor': '#333333',
  'custom-linkFont': 'normal normal normal 24px/1.4em avenir-lt-w01_35-light1475496,sans-serif',
  'custom-linkFontFamily': undefined,
  'custom-linkFontSize': undefined,
  'custom-linkFontStyle': undefined,
  'custom-linkFontWeight': undefined,
  'custom-linkLineHeight': undefined,
  'custom-linkTextDecoration': undefined,
  'custom-pColor': '#333333',
  'custom-pFont': 'normal normal normal 28px/1.4em lulo-clean-w01-one-bold,sans-serif',
  'custom-pFontFamily': undefined,
  'custom-pFontSize': undefined,
  'custom-pFontStyle': undefined,
  'custom-pFontWeight': undefined,
  'custom-pLineHeight': undefined,
  'custom-pTextDecoration': undefined,
  'custom-quoteColor': '#333333',
  'custom-quoteFont': 'normal normal normal 15px/1.4em avenir-lt-w01_35-light1475496,sans-serif',
  'custom-quoteFontFamily': undefined,
  'custom-quoteFontSize': undefined,
  'custom-quoteFontStyle': undefined,
  'custom-quoteFontWeight': undefined,
  'custom-quoteLineHeight': undefined,
  'custom-quoteTextDecoration': undefined,
};
