export const mockWixTypography = {
  Title: {
    editorKey: 'font_0',
    lineHeight: '1.4em',
    style: 'normal',
    weight: 'normal',
    size: '95px',
    fontFamily: 'lulo-clean-w01-one-bold',
    value: 'font:normal normal normal 95px/1.4em lulo-clean-w01-one-bold,sans-serif;',
  },
  Menu: {
    editorKey: 'font_1',
    lineHeight: '1.4em',
    style: 'normal',
    weight: 'normal',
    size: '16px',
    fontFamily: 'din-next-w01-light',
    value:
      'font:normal normal normal 16px/1.4em din-next-w01-light,din-next-w02-light,din-next-w10-light,sans-serif;',
  },
  'Page-title': {
    editorKey: 'font_2',
    lineHeight: '1.4em',
    style: 'normal',
    weight: 'normal',
    size: '28px',
    fontFamily: 'avenir-lt-w01_35-light1475496',
    value: 'font:normal normal normal 28px/1.4em avenir-lt-w01_35-light1475496,sans-serif;',
  },
  'Heading-XL': {
    editorKey: 'font_3',
    lineHeight: '1.4em',
    style: 'normal',
    weight: 'normal',
    size: '119px',
    fontFamily: 'avenir-lt-w01_35-light1475496',
    value: 'font:normal normal normal 119px/1.4em avenir-lt-w01_35-light1475496,sans-serif;',
  },
  'Heading-L': {
    editorKey: 'font_4',
    lineHeight: '1.4em',
    style: 'normal',
    weight: 'normal',
    size: '34px',
    fontFamily: 'lulo-clean-w01-one-bold',
    value: 'font:normal normal normal 34px/1.4em lulo-clean-w01-one-bold,sans-serif;',
  },
  'Heading-M': {
    editorKey: 'font_5',
    lineHeight: '1.4em',
    style: 'normal',
    weight: 'normal',
    size: '28px',
    fontFamily: 'lulo-clean-w01-one-bold',
    value: 'font:normal normal normal 28px/1.4em lulo-clean-w01-one-bold,sans-serif;',
  },
  'Heading-S': {
    editorKey: 'font_6',
    lineHeight: '1.4em',
    style: 'normal',
    weight: 'normal',
    size: '24px',
    fontFamily: 'avenir-lt-w01_35-light1475496',
    value: 'font:normal normal normal 24px/1.4em avenir-lt-w01_35-light1475496,sans-serif;',
  },
  'Body-L': {
    editorKey: 'font_7',
    lineHeight: '1.4em',
    style: 'normal',
    weight: 'normal',
    size: '16px',
    fontFamily: 'avenir-lt-w01_35-light1475496',
    value: 'font:normal normal normal 16px/1.4em avenir-lt-w01_35-light1475496,sans-serif;',
  },
  'Body-M': {
    editorKey: 'font_8',
    lineHeight: '1.4em',
    style: 'normal',
    weight: 'normal',
    size: '15px',
    fontFamily: 'avenir-lt-w01_35-light1475496',
    value: 'font:normal normal normal 15px/1.4em avenir-lt-w01_35-light1475496,sans-serif;',
  },
  'Body-S': {
    editorKey: 'font_9',
    lineHeight: '1.4em',
    style: 'normal',
    weight: 'normal',
    size: '12px',
    fontFamily: 'avenir-lt-w01_35-light1475496',
    value: 'font:normal normal normal 12px/1.4em avenir-lt-w01_35-light1475496,sans-serif;',
  },
  'Body-XS': {
    editorKey: 'font_10',
    lineHeight: '1.4em',
    style: 'normal',
    weight: 'normal',
    size: '12px',
    fontFamily: 'din-next-w01-light',
    value:
      'font:normal normal normal 12px/1.4em din-next-w01-light,din-next-w02-light,din-next-w10-light,sans-serif;',
  },
};

export const mockOutput = {
  'font-body-l': 'normal normal normal 16px/1.4em avenir-lt-w01_35-light1475496,sans-serif',
  'font-body-m': 'normal normal normal 15px/1.4em avenir-lt-w01_35-light1475496,sans-serif',
  'font-body-s': 'normal normal normal 12px/1.4em avenir-lt-w01_35-light1475496,sans-serif',
  'font-body-xs':
    'normal normal normal 12px/1.4em din-next-w01-light,din-next-w02-light,din-next-w10-light,sans-serif',
  'font-heading-l': 'normal normal normal 34px/1.4em lulo-clean-w01-one-bold,sans-serif',
  'font-heading-m': 'normal normal normal 28px/1.4em lulo-clean-w01-one-bold,sans-serif',
  'font-heading-s': 'normal normal normal 24px/1.4em avenir-lt-w01_35-light1475496,sans-serif',
  'font-heading-xl': 'normal normal normal 119px/1.4em avenir-lt-w01_35-light1475496,sans-serif',
  'font-menu':
    'normal normal normal 16px/1.4em din-next-w01-light,din-next-w02-light,din-next-w10-light,sans-serif',
  'font-page-title': 'normal normal normal 28px/1.4em avenir-lt-w01_35-light1475496,sans-serif',
  'font-title': 'normal normal normal 95px/1.4em lulo-clean-w01-one-bold,sans-serif',
};
