name: tests
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
env:
  captureVideos: 'true'
  captureImages: 'true'
  COMMIT_SHA: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.sha || github.sha }}

jobs:
  cleanup-runs:
    runs-on: ubuntu-latest
    steps:
      - uses: rokroskar/workflow-run-cleanup-action@v0.3.3
        if: "!startsWith(github.ref, 'refs/tags/') && github.ref != 'refs/heads/master'"
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'

  e2e-visual:
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        ci_node_total: [4] # Set N number of parallel jobs you want to run tests on.
        ci_node_index: [0, 1, 2, 3] # set N-1 indexes for parallel jobs

    steps:
      - uses: actions/checkout@v2
      - id: cache
        uses: actions/cache@master
        with:
          path: |
            node_modules
            */*/node_modules
            ~/.cache
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
      - name: Install Protoc
        uses: arduino/setup-protoc@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: npm install + bootstrap
        if: steps.cache.outputs.cache-hit != 'true'
        run: npx midgard-yarn install --frozen-lockfile
      - name: lerna link
        if: steps.cache.outputs.cache-hit == 'true'
        run: npm run link
      - name: build
        run: npm run build:test
      - name: Run http server with the app in the background
        run: |
          npm run e2e:app:run &
      - name: Wait for server to initialize
        run: |
          npm run e2e:app:wait

      - name: Run tests with Knapsack Pro
        env:
          KNAPSACK_PRO_TEST_SUITE_TOKEN_CYPRESS: ${{ secrets.KNAPSACK_PRO_TEST_SUITE_TOKEN_CYPRESS }}
          #          KNAPSACK_PRO_CI_NODE_BUILD_ID: $(openssl rand -base64 32)
          KNAPSACK_PRO_FIXED_QUEUE_SPLIT: true
          KNAPSACK_PRO_CI_NODE_TOTAL: ${{ matrix.ci_node_total }}
          KNAPSACK_PRO_CI_NODE_INDEX: ${{ matrix.ci_node_index }}
          KNAPSACK_PRO_TEST_FILE_PATTERN: 'e2e/tests/*.e2e.js'
          APPLITOOLS_API_KEY: ${{ secrets.APPLITOOLS_API_KEY }}
          APPLITOOLS_SERVER_URL: ${{ secrets.APPLITOOLS_SERVER_URL }}
        run: |
          # fix video recording bug
          echo -e 'pcm.!default {\n type hw\n card 0\n}\n\nctl.!default {\n type hw\n card 0\n}' > ~/.asoundrc
          $(npm bin)/knapsack-pro-cypress
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: cypress-screenshots-${{ matrix.ci_node_index }}
          path: |
            e2e/cypress/screenshots
            e2e/cypress/videos
            **/applitools.log

  e2e-visual-applitoolsSendCompletion:
    needs: e2e-visual
    if: always()
    runs-on: ubuntu-18.04
    steps:
      - name: Update Applitools batch status
        uses: wei/curl@v1.1.1
        with:
          args: -d "" -X POST https://wixeyesapi.applitools.com/api/externals/github/servers/github.com/commit/${{ env.COMMIT_SHA }}/complete?apiKey=${{ secrets.APPLITOOLS_API_KEY }}

  content-state-tests:
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        ci_node_total: [3] # Set N number of parallel jobs you want to run tests on.
        ci_node_index: [0, 1, 2] # set N-1 indexes for parallel jobs

    steps:
      - uses: actions/checkout@v2
      - name: cache
        id: cache
        uses: actions/cache@master
        with:
          path: |
            node_modules
            */*/node_modules
            ~/.cache
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
      - name: Install Protoc
        uses: arduino/setup-protoc@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: npm install + bootstrap
        if: steps.cache.outputs.cache-hit != 'true'
        run: npx midgard-yarn install --frozen-lockfile
      - name: lerna link
        if: steps.cache.outputs.cache-hit == 'true'
        run: npm run link
      - name: build
        run: npm run build:test
      - name: Run http server with the app in the background
        run: npm run e2e:app:run & npm run e2e:app:wait

      - name: Run tests with Knapsack Pro
        env:
          KNAPSACK_PRO_TEST_SUITE_TOKEN_CYPRESS: ${{ secrets.KNAPSACK_PRO_TEST_SUITE_TOKEN_CYPRESS }}
          #          KNAPSACK_PRO_CI_NODE_BUILD_ID: $(openssl rand -base64 32)
          KNAPSACK_PRO_FIXED_QUEUE_SPLIT: true
          KNAPSACK_PRO_CI_NODE_TOTAL: ${{ matrix.ci_node_total }}
          KNAPSACK_PRO_CI_NODE_INDEX: ${{ matrix.ci_node_index }}
          KNAPSACK_PRO_TEST_FILE_PATTERN: 'e2e/tests/*.e2e.js'
          APPLITOOLS_IS_DISABLED: true
        run: |
          # fix video recording bug
          echo -e 'pcm.!default {\n type hw\n card 0\n}\n\nctl.!default {\n type hw\n card 0\n}' > ~/.asoundrc
          $(npm bin)/knapsack-pro-cypress --env MATCH_CONTENT_STATE=true
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: cypress-screenshots-${{ matrix.ci_node_index }}
          path: |
            e2e/cypress/screenshots
            e2e/cypress/videos
            **/applitools.log

  lint-and-unit-tests:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: cache
        id: cache
        uses: actions/cache@master
        with:
          path: |
            node_modules
            */*/node_modules
            ~/.cache
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
      - name: Install Protoc
        uses: arduino/setup-protoc@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: npm install + bootstrap
        if: steps.cache.outputs.cache-hit != 'true'
        run: npx midgard-yarn install --frozen-lockfile
      - name: lerna link
        if: steps.cache.outputs.cache-hit == 'true'
        run: npm run link

      - run: npm run lint
      - run: npm run build
      - run: npm run test

  notify-on-slack:
    runs-on: ubuntu-18.04
    needs: [e2e-visual, content-state-tests, lint-and-unit-tests]
    if: always()
    steps:
      - name: Get commit author
        id: commit-author
        run: |
          echo "commit-author=$(curl -s https://api.github.com/repos/wix/ricos/commits/${{ env.COMMIT_SHA }} | jq '.author.login' | sed 's/\"//g')" >> $GITHUB_ENV
      - name: Get PR number
        id: pr-number
        run: |
          echo "pr-number=$(curl -s https://api.github.com/repos/wix/ricos/commits/${{ env.COMMIT_SHA }} | jq '.commit.message' | sed 's/.*(#//g' | sed 's/[^0-9]//g')" >> $GITHUB_ENV
      - name: Notify fail in Slack
        uses: voxmedia/github-action-slack-notify-build@v1.1.3
        if: github.ref == 'refs/heads/master' && (needs.e2e-visual.result == 'failure' || needs.content-state-tests.result == 'failure' || needs.lint-and-unit-tests.result == 'failure')
        with:
          channel_id: C0124DH7HHS #ricos-ci
          status: FAILED ${{ env[env.commit-author] }}
          color: danger

      # - name: Get current commit status
      #   id: current-status
      #   run: |
      #     echo "::set-output name=current-status::$(echo $(curl -s https://api.github.com/repos/wix/ricos/commits/${{ env.COMMIT_SHA }}/check-suites\?app_id\=15368 -H "Accept: application/vnd.github.antiope-preview+json" | jq '.check_suites | [.[] | select( .head_branch == "master") | .conclusion] | .[:2] | .[]' | sed 's/\"//g'))"
      - name: Get previous commit
        id: previous-commit
        run: |
          echo "previous-commit=$(curl -s https://api.github.com/repos/wix/ricos/commits/${{ env.COMMIT_SHA }} | jq '.parents[0].sha' | sed 's/\"//g')"  >> $GITHUB_ENV
      # - name: Get previous commit status
      #   id: previous-status
      #   run: |
      #     echo "::set-output name=previous-status::$(echo $(curl -s https://api.github.com/repos/wix/ricos/commits/${{ steps.previous-commit.outputs.previous-commit }}/check-suites\?app_id\=15368 -H "Accept: application/vnd.github.antiope-preview+json" | jq '.check_suites | [.[] | select( .head_branch == "master") | .conclusion] | .[:2] | .[]' | sed 's/\"//g'))"
      - name: Get previous commit status
        id: previous-status
        run: |
          echo "previous-status=$(echo $(curl -s https://api.github.com/repos/wix/ricos/actions/workflows/tests.yml/runs\?branch\=master | jq '.workflow_runs | .[] | select( .head_sha == "${{ env.previous-commit }}") | .conclusion' | sed 's/\"//g'))" >> $GITHUB_ENV
      - name: Notify recovery in Slack
        uses: voxmedia/github-action-slack-notify-build@v1.1.3
        if: github.ref == 'refs/heads/master' && env.previous-status == 'failure' && (needs.e2e-visual.result == 'success' && needs.content-state-tests.result == 'success' && needs.lint-and-unit-tests.result == 'success')
        with:
          channel_id: C0124DH7HHS #ricos-ci
          status: 'RECOVERED  :celebrate:'
          color: '#28a745'
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      Barackos: <@UM3M904MU>
      danarish4: <@UEBDPSU2W>
      lxgreen: <@U6FQCJ5GT>
      maimonav: <@UMUB0DSLD>
      mharsat: <@UJAAZU58B>
      noamtwix: <@UEBDQJBMG>
      oded-soffrin: <@U0MN7A3H8>
      shaulgo: <@U0SDJ5S30>
      talevy17: <@UM24QHHAR>
      tamrat-bay: <@U01E6AJC4AV>
      justame: <@U06D4H3MJ>
      wix-babel-ng: ' - Babel added new translations :pokesquirtlewalk:'
